kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  # web
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  # websecure
  - containerPort: 443
    hostPort: 443
    protocol: TCP
  # rabbitmq
  - containerPort: 5672
    hostPort: 5672
    protocol: TCP
  # nats
  - containerPort: 4222
    hostPort: 4222
    protocol: TCP
- role: worker
- role: worker
