version: "3.7"

services:

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    networks:
      - private_brokers
    ports:
      - 15432:80

  timescale:
    image: timescale/timescaledb:1.7.4-pg12
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      TS_TUNE_NUM_CPUS: 1
      TS_TUNE_MEMORY: 2GB
    volumes:
      - timescale_data:/var/lib/postgresql/data
    networks:
      - private_brokers
    ports:
      - 5432:5432

  nats:
    image: "bitnami/nats:2-debian-10"
    command: >
      --http_port 8222
      --user admin
      --pass password
    networks:
      - private_brokers
    ports:
      - 4222:4222

  rabbitmq:
    image: "bitnami/rabbitmq:3.8-debian-10"
    environment:
      RABBITMQ_USERNAME: "admin"
      RABBITMQ_PASSWORD: "password"
    volumes:
      - rabbitmq_data:/bitnami
    networks:
      - private_brokers
    ports:
      - 5672:5672
      - 15672:15672

volumes:

  timescale_data:
  rabbitmq_data:

networks:

  private_brokers:
    driver: overlay
    name: private_brokers
