argo-cd:
  server:
    additionalApplications:
      - name: moleculer
        project: default
        source:
          repoURL: 'https://github.com/gperreymond/moleculer-data-pipelines.git'
          path: applications
          targetRevision: main
        destination:
          server: 'https://kubernetes.default.svc'
          namespace: moleculer
        syncPolicy:
          automated:
            prune: true
          syncOptions:
            - CreateNamespace=true
    config:
      url: https://argocd.docker.localhost
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      hosts:
        - argocd.docker.localhost
