[sources.prometheus_rabbitmq]
  type = "prometheus_scrape"
  endpoints = ["http://rabbitmq.moleculer:9419/metrics"]
  scrape_interval_secs = 30

# [transforms.metric_to_log]
#   type = "metric_to_log"
#   inputs = ["prometheus_rabbitmq"]

[sinks.moleculer]
  # General
  type = "nats" # required
  inputs = ["prometheus_rabbitmq"]
  healthcheck = true
  subject = "SinksDomain.MessageToMoleculer.Queue"
  url = "nats://nats-headless.moleculer:4222"
  # Encoding
  encoding.codec = "json"

[sinks.console]
  # General
  type = "console"
  inputs = ["prometheus_rabbitmq"]
  target = "stdout"
  # Encoding
  encoding.codec = "json"
