[sources.http_id]
  # General
  type = "http"
  address = "0.0.0.0:80"
  # Encoding
  encoding = "json"

[sinks.moleculer_id]
  # General
  type = "nats" # required
  inputs = ["http_id"]
  healthcheck = true
  subject = "SinksDomain.MessageToMoleculer.Queue"
  url = "nats://nats-headless.moleculer:4222"
  # Encoding
  encoding.codec = "json"

[sinks.console_id]
  # General
  type = "console"
  inputs = ["http_id"]
  target = "stdout"
  # Encoding
  encoding.codec = "json"
