apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vector-block-sources
spec:
  rules:
    - host: vector.docker.localhost
      http:
        paths:
          - path: /
            backend:
              service:
                name: vector-block-sources
                port:
                  number: 80
