ingress-nginx:
  revisionHistoryLimit: 2
  tcp:
    4222: "moleculer/nats-client:4222"
    5672: "moleculer/rabbitmq:5672"
  controller:
    hostPort:
      enabled: true
    extraArgs:
      enable-ssl-passthrough: ""
    service:
      type: ClusterIP
    tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Equal"
      effect: "NoSchedule"
    nodeSelector:
      "ingress-ready": "true"
