ingress-nginx:
  controller:
    extraArgs:
      enable-ssl-passthrough: ""
    hostPort:
      enabled: true
      ports:
        http: 80
        https: 443
    service:
      type: ClusterIP
    tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Equal"
      effect: "NoSchedule"
    nodeSelector:
      "ingress-ready": "true"
